var CodeMirror;
function CodeMirror(){};
CodeMirror.fromTextArea = {};
CodeMirror.refresh = {};
CodeMirror.getValue = {};
CodeMirror.setValue = {};
CodeMirror.setSize = {};
var $;
function $(){};
$.on = {};
